global using System.CommandLine;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using System.Text.RegularExpressions;
global using CommunityToolkit.Diagnostics;
global using GenerateTokenJwt.Sample.Extensions;
global using GenerateTokenJwt.Sample.Payloads;
global using Microsoft.IdentityModel.Tokens;